title:              Jungsoo
email:              jsh562@nyu.edu
description:        Data / Journalism
author:             Jungsoo
baseurl:            ""
url:                "https://hawill10.github.io"

# Social Profiles
twitter_username:   
github_username:  hawill10
facebook_username:  
instagram_username:  
linkedin_username:  jung-soo-ha-3967a9170  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
